export const SOCKET_RUNNING = 'Socket is already running'
export const SOCKET_INITIALIZING = 'Socket is initializing'
export const SOCKET_LISTEN_TO_COMMENT = 'comment'
export const SOCKET_BROADCAST_ADD_COMMENT_EVENT = 'add-comment'
export const SOCKET_CONNECTED = 'socket connected'
export const SOCKET_DISCONNECTED = 'socket disconnected'
